[package]
name = "codora"
version = "0.1.0"
edition = "2021"


[features]
default = ["new"]
new = []
axum = []
validator = []

[dependencies]
serde = { workspace = true }
tower-layer = "0.3.3"
anyhow.workspace = true
tokio = { version = "1.44.0", features = ["full"] }
derive-new = "0.7.0"

[dev-dependencies]
tokio = { version = "1.44.0", features = ["full"] }


[workspace]
members = [".", "crates/*"]
resolver = "2"


[workspace.lints.clippy]

[workspace.package]
version = "0.8.3"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/getcodora/codora"
# TODO Add other important keyword!
keywords = ["authentication", "authorization", "codora"]
categories = ["web-programming", "security", "authentication", "authorization"]
authors = ["West Sheriff <west.sh.mail@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.87"
serde = "1.0.215"
